export const races = [
  {
    name: "blood elf",
    available_classes: [
      "warrior",
      "hunter",
      "mage",
      "rogue",
      "priest",
      "warlock",
      "paladin",
      "monk",
      "demon hunter",
      "death knight",
    ],
  },
  {
    name: "human",
    available_classes: [
      "warrior",
      "hunter",
      "mage",
      "rogue",
      "priest",
      "warlock",
      "paladin",
      "monk",
      "death knight",
    ],
  },
  {
    name: "gnome",
    available_classes: [
      "warrior",
      "hunter",
      "mage",
      "rogue",
      "priest",
      "warlock",
      "monk",
      "death knight",
    ],
  },
  {
    name: "void elf",
    available_classes: [
      "warrior",
      "hunter",
      "mage",
      "rogue",
      "priest",
      "warlock",
      "monk",
      "death knight",
    ],
  },
  {
    name: "undead",
    available_classes: [
      "warrior",
      "hunter",
      "mage",
      "rogue",
      "priest",
      "warlock",
      "monk",
      "death knight",
    ],
  },
  {
    name: "tauren",
    available_classes: [
      "warrior",
      "hunter",
      "mage",
      "rogue",
      "priest",
      "warlock",
      "paladin",
      "druid",
      "shaman",
      "monk",
      "death knight",
    ],
  },
  {
    name: "draenei",
    available_classes: [
      "warrior",
      "hunter",
      "mage",
      "rogue",
      "priest",
      "warlock",
      "paladin",
      "monk",
      "death knight",
      "shaman",
    ],
  },
  {
    name: "nightborne",
    available_classes: [
      "warrior",
      "hunter",
      "mage",
      "rogue",
      "priest",
      "warlock",
      "monk",
      "death knight",
    ],
  },
  {
    name: "highmountain tauren",
    available_classes: [
      "warrior",
      "hunter",
      "mage",
      "rogue",
      "priest",
      "warlock",
      "druid",
      "shaman",
      "monk",
      "death knight",
    ],
  },
  {
    name: "mag'har orc",
    available_classes: [
      "warrior",
      "hunter",
      "mage",
      "rogue",
      "priest",
      "warlock",
      "shaman",
      "monk",
      "death knight",
    ],
  },
  {
    name: "zandalari troll",
    available_classes: [
      "warrior",
      "hunter",
      "mage",
      "rogue",
      "priest",
      "warlock",
      "paladin",
      "druid",
      "shaman",
      "monk",
      "death knight",
    ],
  },
  {
    name: "vulpera",
    available_classes: [
      "warrior",
      "hunter",
      "mage",
      "rogue",
      "priest",
      "warlock",
      "shaman",
      "monk",
      "death knight",
    ],
  },
  {
    name: "troll",
    available_classes: [
      "warrior",
      "hunter",
      "mage",
      "rogue",
      "priest",
      "warlock",
      "druid",
      "shaman",
      "monk",
      "death knight",
    ],
  },
  // "night elf",s
  {
    name: "goblin",
    available_classes: [
      "warrior",
      "hunter",
      "mage",
      "rogue",
      "priest",
      "warlock",
      "shaman",
      "monk",
      "death knight",
    ],
  },
  {
    name: "worgen",
    available_classes: [
      "warrior",
      "hunter",
      "mage",
      "rogue",
      "priest",
      "warlock",
      "druid",
      "monk",
      "death knight",
    ],
  },
  {
    name: "orc",
    available_classes: [
      "warrior",
      "hunter",
      "mage",
      "rogue",
      "priest",
      "warlock",
      "monk",
      "death knight",
      "shaman",
    ],
  },
  {
    name: "pandaren",
    available_classes: [
      "warrior",
      "hunter",
      "mage",
      "rogue",
      "priest",
      "warlock",
      "monk",
      "death knight",
      "shaman",
    ],
  },
  { name: "dracthyr", available_classes: ["evoker"] },
  {
    name: "lightforged draenei",
    available_classes: [
      "warrior",
      "hunter",
      "mage",
      "rogue",
      "priest",
      "warlock",
      "paladin",
      "monk",
      "death knight",
    ],
  },
  {
    name: "dark iron dwarf",
    available_classes: [
      "warrior",
      "hunter",
      "mage",
      "rogue",
      "priest",
      "warlock",
      "paladin",
      "shaman",
      "monk",
      "death knight",
    ],
  },
  {
    name: "kul tiran",
    available_classes: [
      "warrior",
      "hunter",
      "mage",
      "rogue",
      "priest",
      "warlock",
      "druid",
      "shaman",
      "monk",
      "death knight",
    ],
  },
  {
    name: "mechagnone",
    available_classes: [
      "warrior",
      "hunter",
      "mage",
      "rogue",
      "priest",
      "warlock",
      "monk",
      "death knight",
    ],
  },
];
